In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv", encoding="latin-1")

In [3]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 677.1 KB

In [5]:
df = df[['v1', 'v2']]

In [6]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.columns = ['label', 'message']

In [8]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.shape

(5572, 2)

In [10]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [11]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [12]:
df.sample(10)

     label                                            message
3062  spam  Hi babe its Jordan, how r u? Im home from abro...
2999   ham    Id onluy matters when getting on from offcampus
961   spam  URGENT! We are trying to contact U. Todays dra...
3638   ham                    Wat's da model num of ur phone?
1684   ham                     Do you want bold 2 or bb torch
762   spam  Urgent Ur å£500 guaranteed award is still uncl...
5180   ham  Babe! I fucking love you too !! You know? Fuck...
4235  spam  U can WIN å£100 of Music Gift Vouchers every w...
33     ham  For fear of fainting with the of all that hous...
143    ham         I know you are. Can you pls open the back?

In [14]:
df['label'] = df['label'].map({'ham':0, 'spam':1})

In [15]:
df.head()

   label                                            message
0    NaN  Go until jurong point, crazy.. Available only ...
1    NaN                      Ok lar... Joking wif u oni...
2    NaN  Free entry in 2 a wkly comp to win FA Cup fina...
3    NaN  U dun say so early hor... U c already then say...
4    NaN  Nah I don't think he goes to usf, he lives aro...

In [16]:
X = df['message']
y = df['label']

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
print(X_train.shape)
print(X_test.shape)

(4457,)
(1115,)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
vectorizer = TfidfVectorizer()

In [23]:
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [24]:
print(X_train.shape)

(4457, 7735)

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
model = MultinomialNB()

In [28]:
model.fit(X_train, y_train)

ValueError: Input y contains NaN.

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

AttributeError: 'csr_matrix' object has no attribute 'lower'

In [30]:
df.head()

   label                                            message
0    NaN  Go until jurong point, crazy.. Available only ...
1    NaN                      Ok lar... Joking wif u oni...
2    NaN  Free entry in 2 a wkly comp to win FA Cup fina...
3    NaN  U dun say so early hor... U c already then say...
4    NaN  Nah I don't think he goes to usf, he lives aro...

In [31]:
print(df['message'].dtype)

str

In [32]:
print(df.isnull().sum())

label      5572
message       0
dtype: int64

In [33]:
print(type(X_train))
print(X_train.head())

<class 'scipy.sparse._csr.csr_matrix'>

AttributeError: 'csr_matrix' object has no attribute 'head'

In [34]:
print(type(X))
print(type(y))

<class 'pandas.Series'>
<class 'pandas.Series'>

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(type(X_train))

<class 'pandas.Series'>

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)

print(type(X_train))

<class 'scipy.sparse._csr.csr_matrix'>

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

ValueError: Input y contains NaN.

In [38]:
print(X_train.shape)
print(y_train.shape)

(4457, 7735)
(4457,)

In [39]:
print(y_train.unique())

[nan]

In [40]:
import pandas as pd

df = pd.read_csv("spam.csv", encoding="latin-1")
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

In [41]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [42]:
print(df.head())
print(df['label'].unique())
print(df['label'].isnull().sum())

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
[0 1]
0

In [43]:
X = df['message']
y = df['label']

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [46]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [47]:
message = ["Congratulations! You have won a FREE iPhone. Click here to claim your prize now."]

message_vector = vectorizer.transform(message)

prediction = model.predict(message_vector)

if prediction[0] == 1:
    print("🚨 Spam Email")
else:
    print("✅ Not Spam")

🚨 Spam Email

In [48]:
message = ["Hi Pranathi, are we meeting at 5 PM today?"]

message_vector = vectorizer.transform(message)

prediction = model.predict(message_vector)

if prediction[0] == 1:
    print("🚨 Spam Email")
else:
    print("✅ Not Spam")

✅ Not Spam

In [49]:
import joblib

In [50]:
joblib.dump(model, "model.pkl")

['model.pkl']

In [51]:
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']